[package]
name = "missionplanner_desktop"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
mavkit = { path = "../../../crates/mavkit" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["sync"] }
serialport = "4"

[features]
custom-protocol = ["tauri/custom-protocol"]
